import mongoose from "mongoose";

const customer_querySchema=mongoose.Schema({
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "projects",
      required: true
    },
    name:{
        type:String,
        required:[true,"Name is required"]
    },
    phone:{
        type:String,
        required:[true,"Phone number is required"]
    },
    queryType:String,
    description:String,
    status:{
        type:String,
        enum:["pending","in-progress","resolved"],
        default:"pending"
    }
},
{
    timestamps:true
})

const CustomerQueryModel=mongoose.model("customer_queries",customer_querySchema)
export default CustomerQueryModel;

/*
Step
🔹 Step 1 – Customer enters mobile number

Backend flow:
Receive mobile number
Search in projects collection:

const project = await ProjectModel.findOne({ phone: req.body.phone });

🔹 Step 2 – If NOT Found

If project === null:

👉 Return response:

return res.status(404).json({
  message: "No installed project found. Please request service or site visit."
});

Frontend will redirect to:
Request Service
Site Visit

Perfect UX flow 👌

🔹 Step 3 – If Found

If project exists:

const newQuery = await CustomerQueryModel.create({
  customerId: project._id,
  name: project.name,
  phone: project.phone,
  queryType,
  description
});

So:
_id → auto generated by MongoDB
customerId → stores reference to project
name + phone → stored for quick admin display
*/

/*
Why Keep Both customerId AND name/phone?

You might ask:

If we store customerId, why also store name & phone?

Answer:

🔥 Because:

If in future:
Customer updates phone
Name spelling changes
Project document changes
Old queries still show original data.

This is called:
Snapshotting important data

Very good design choice.
*/

